### ISSUE TITLE
Unclear status on failure

### ISSUE THREAD

**Issue by NathanReb** [dune-universe/duniverse-lint#2]
From the README I understood that the tool already perform two checks. I ran it on a port I'm working on and it only gave one error:
```
$ duniverse-lint
Version is missing +dune
```

It's unclear in the output whether that's the only thing that needs fixing or if I need to run it again once it's fixed.

What would you think about running all checks all the time and reporting their success or failure all at once both for clarity and ease of use?

**Comment by Leonidas-from-XIV** [comment]
Yes, I agree it would be better not to error out so early. I'll make the error handling a bit better.
